[supervisord]
loglevel=info
logfile=/code/.local/supervisord.log
pidfile=/run/supervisord.pid

[unix_http_server]
file=/run/supervisor.sock

[supervisorctl]
serverurl=unix:///run/supervisor.sock
user=root

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:code-server]
command=/etc/code-docker/code-service.sh
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:sshd]
command=/etc/code-docker/sshd-service.sh
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:tailscaled]
command=/etc/code-docker/tailscale-service.sh
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:tailscale-forward]
command=/etc/code-docker/tailscale-forward.sh
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:tailscale-status]
command=/etc/code-docker/tailscale-status.sh
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:webmanager]
command=/etc/code-docker/webmanager.sh
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[include]
files = /etc/code-docker/supervisord/*.conf
